/* include/libstdf_sys_config.h.  Generated by configure.  */
/* include/libstdf_sys_config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <assert.h> header file. */
#define HAVE_ASSERT_H 1

/* Define to 1 if you have the <byteswap.h> header file. */
/* #undef HAVE_BYTESWAP_H */

/* Has bzip2 support */
/* #undef HAVE_BZIP2 */

/* Define to 1 if you have the <bzlib.h> header file. */
/* #undef HAVE_BZLIB_H */

/* Define to 1 if you have the <cmplrs/host.h> header file. */
/* #undef HAVE_CMPLRS_HOST_H */

/* Define to 1 if you have the <ctype.h> header file. */
#define HAVE_CTYPE_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <dmalloc.h> header file. */
/* #undef HAVE_DMALLOC_H */

/* Has ecore support (used by example programs) */
/* #undef HAVE_ECORE */

/* Define to 1 if you have the <efence.h> header file. */
/* #undef HAVE_EFENCE_H */

/* Define to 1 if you have the <endian.h> header file. */
/* #undef HAVE_ENDIAN_H */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <features.h> header file. */
/* #undef HAVE_FEATURES_H */

/* Has gd support (used by example programs) */
#define HAVE_GDLIB 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Has glib support (used by example programs) */
#define HAVE_GLIB 1

/* Has gzip support */
/* #undef HAVE_GZIP */

/* Define to 1 if you have the <hash.h> header file. */
/* #undef HAVE_HASH_H */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `c' library (-lc). */
/* #undef HAVE_LIBC */

/* Define to 1 if you have the `dmalloc' library (-ldmalloc). */
/* #undef HAVE_LIBDMALLOC */

/* Define to 1 if you have the `efence' library (-lefence). */
/* #undef HAVE_LIBEFENCE */

/* Define to 1 if you have the `mudflap' library (-lmudflap). */
/* #undef HAVE_LIBMUDFLAP */

/* Has lzw support */
/* #undef HAVE_LZW */

/* Define to 1 if you have the <machine/endian.h> header file. */
#define HAVE_MACHINE_ENDIAN_H 1

/* Define to 1 if you have the <mcheck.h> header file. */
/* #undef HAVE_MCHECK_H */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdarg.h> header file. */
#define HAVE_STDARG_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/cdefs.h> header file. */
#define HAVE_SYS_CDEFS_H 1

/* Define to 1 if you have the <sys/endian.h> header file. */
/* #undef HAVE_SYS_ENDIAN_H */

/* Define to 1 if you have the <sys/isa_defs.h> header file. */
/* #undef HAVE_SYS_ISA_DEFS_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Has zip support */
/* #undef HAVE_ZIP */

/* Define to 1 if you have the <zlib.h> header file. */
/* #undef HAVE_ZLIB_H */

/* Name of package */
#define PACKAGE "libstdf"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "vapier@gmail.com"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libstdf"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libstdf 0.4"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libstdf"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.4"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Force endian type to big */
/* #undef STDF_FORCE_ENDIAN */

/* Enable support for STDFv3 */
/* #undef STDF_VER3 */

/* Version number of package */
#define VERSION "0.4"

/* Annoy people about unimplemented code */
#define WARN_UNTESTED 1

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `size_t' if <sys/types.h> does not define. */
/* #undef uintptr_t */

#define __IN_LIBSTDF 1
